title: Disable Windows Defender and SmartScreen
actions:
- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender'
    value: 'AllowFastServiceStartup'
    data: '0'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender'
    value: 'DisableAntiSpyware'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender'
    value: 'DisableAntiVirus'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender'
    value: 'DisableSpecialRunningModes'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Microsoft\Windows Defender\Features'
    value: 'TamperProtection'
    data: '0'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender'
    value: 'ServiceKeepAlive'
    data: '0'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender\MpEngine'
    value: 'MpEnablePus'
    data: '0'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
    value: 'DisableBehaviorMonitoring'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
    value: 'DisableIOAVProtection'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
    value: 'DisableOnAccessProtection'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
    value: 'DisableRealtimeMonitoring'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
    value: 'DisableRoutinelyTakingAction'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
    value: 'DisableScanOnRealtimeEnable'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Reporting'
    value: 'DisableEnhancedNotifications'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender\SpyNet'
    value: 'DisableBlockAtFirstSeen'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender\SpyNet'
    value: 'SpynetReporting'
    data: '0'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows Defender\SpyNet'
    value: 'SubmitSamplesConsent'
    data: '2'
    type: REG_DWORD

- !registryValue:
    path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender'
    value: 'DisableAntiSpyware'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System'
    value: 'EnableSmartScreen'
    data: '0'
    type: REG_DWORD