title: APPX Removal
actions:
    # Remove Microsoft Store (APPX) apps
  - !appx: {name: '*MicrosoftTeams*', type: family}
  - !appx: {name: 'Clipchamp.Clipchamp*', type: family}
  - !appx: {name: 'Disney.37853FC22B2CE*', type: family}
  - !appx: {name: 'SpotifyAB.SpotifyMusic*', type: family}
  - !appx: {name: 'Microsoft.549981C3F5F10*', type: family} # Cortana
  - !appx: {name: 'Microsoft.XboxApp*', type: family} # Xbox Console Companion (deprecated)
  - !appx: {name: 'microsoft.windowscommunicationsapps*', type: family} # Mail and Calendar
  - !appx: {name: 'Microsoft.MSPaint*', type: family} # Paint 3D
  - !appx: {name: 'Microsoft.Getstarted*', type: family} # Tips (deprecated)
  - !appx: {name: 'Microsoft.ZuneVideo*', type: family} # Films & TV
  - !appx: {name: 'MicrosoftCorporationII.MicrosoftFamily*', type: family}
  - !appx: {name: 'Microsoft.MixedReality.Portal*', type: family}
  - !appx: {name: 'Microsoft.Windows.DevHome*', type: family}
  - !appx: {name: 'Microsoft.BingWeather*', type: family}
  - !appx: {name: 'Microsoft.BingNews*', type: family}
  - !appx: {name: 'Microsoft.BingSearch*', type: family}
  - !appx: {name: 'Microsoft.OutlookForWindows*', type: family}
  - !appx: {name: 'Microsoft.GetHelp*', type: family}
  - !appx: {name: 'Microsoft.Microsoft3DViewer*', type: family}
  - !appx: {name: 'Microsoft.MicrosoftOfficeHub*', type: family}
  - !appx: {name: 'Microsoft.MicrosoftSolitaireCollection*', type: family}
  - !appx: {name: 'Microsoft.MicrosoftStickyNotes*', type: family}
  - !appx: {name: 'Microsoft.Office.OneNote*', type: family}
  - !appx: {name: 'Microsoft.People*', type: family}
  - !appx: {name: 'Microsoft.PowerAutomateDesktop*', type: family}
  - !appx: {name: 'Microsoft.SkypeApp*', type: family}
  - !appx: {name: 'Microsoft.Todos*', type: family}
  - !appx: {name: 'Microsoft.WindowsAlarms*', type: family}
  - !appx: {name: 'Microsoft.WindowsCamera*', type: family}
  - !appx: {name: 'Microsoft.WindowsFeedbackHub*', type: family}
  - !appx: {name: 'Microsoft.WindowsMaps*', type: family}
  - !appx: {name: 'Microsoft.WindowsSoundRecorder*', type: family}
  - !appx: {name: 'Microsoft.Windows.Photos*', type: family}
  - !appx: {name: 'Microsoft.XboxIdentityProvider*', type: family}
  - !appx: {name: 'Microsoft.ECApp*', type: family}
  - !appx: {name: 'Microsoft.AsyncTextService*', type: family}
  - !appx: {name: 'Microsoft.ZuneMusic*', type: family}
  - !appx: {name: 'Microsoft.YourPhone*', type: family}
  - !appx: {name: 'Microsoft.XboxSpeechToTextOverlay*', type: family}
  - !appx: {name: 'Microsoft.XboxGamingOverlay*', type: family}
  - !appx: {name: 'Microsoft.XboxGameOverlay*', type: family}
  - !appx: {name: 'Microsoft.Xbox.TCUI*', type: family}
  - !appx: {name: 'Microsoft.Wallet*', type: family}

  - !powerShell:
    command: |
      Get-AppxPackage Microsoft.YourPhone* | Remove-AppxPackage
      Get-AppxProvisionedPackage -Online | Where-Object { $_.DisplayName -eq 'Microsoft.YourPhone' } | Remove-AppxProvisionedPackage -Online
    runas: currentUserElevated
    wait: true

    # Windows 11
  - !appx: {name: 'Microsoft.Paint*', type: family}
  - !appx: {name: 'Microsoft.CorporationII.QuickAssist*', type: family}
  - !appx: {name: 'Microsoft.WindowsTerminal*', type: family}
  - !appx: {name: 'Microsoft.YourPhone*', type: family}
  - !appx: {name: 'Microsoft.GamingApp*', type: family}
  - !appx: {name: 'Microsoft.Windows.NarratorQuickStart*', type: family}
  - !appx: {name: 'MicrosoftCorporationII.QuickAssist*', type: family}
  - !appx: {name: 'Microsoft.GamingApp*', type: family}
  - !appx: {name: 'MSTeams_*', type: family}

    # Necessary to refresh start menu entries etc.
  - !appx: {name: '*Client.CBS*', operation: clearCache}
  - !appx: {name: '*StartMenuExperienceHost*', operation: clearCache}
  - !appx: {name: '*Windows.Search*', operation: clearCache}
