title: Disable Windows Defender & SmartScreen
actions:
- !registryValue:
    path: 'HKLM\System\CurrentControlSet\Services\WdFilter'
    value: 'Start'
    data: '4'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\System\CurrentControlSet\Services\WdNisDrv'
    value: 'Start'
    data: '4'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\System\CurrentControlSet\Services\WdNisSvc'
    value: 'Start'
    data: '4'
    type: REG_DWORD

- !registryValue:
    path: 'HKLM\System\CurrentControlSet\Services\WinDefend'
    value: 'Start'
    data: '4'
    type: REG_DWORD

- !registryValue:
    path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender'
    value: 'DisableAntiSpyware'
    data: '1'
    type: REG_DWORD

- !registryValue:
    path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System'
    value: 'EnableSmartScreen'
    data: '0'
    type: REG_DWORD