title: Enable cloud protection & tamper prevention option in Defender to improve AV effectiveness 
actions:
- !registryValue:
  path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet'
  value: 'SpynetReporting'
  data: '1'
  type: REG_DWORD

- !registryValue:
  path: 'HKLM\SOFTWARE\Microsoft\Windows Defender\Features'
  value: 'TamperProtection'
  data: '5'
  type: REG_DWORD

  # if ExplorerPatcher was selected to be installed, add exceptions
- !powerShell:
  command: 'Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"; Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"; Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"; Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"; Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy"'
  wait: true
  option: 'install-ep'