title: Quality of life tweaks
actions:
    # verbose status
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
    value: 'VerboseStatus'
    data: '1'
    type: REG_DWORD

    # show all hidden files
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'ShowHidden'
    data: '1'
    type: REG_DWORD

  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'Hidden'
    data: '1'
    type: REG_DWORD

#  - !registryValue:
#    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
#    value: 'ShowSuperHidden'
#    data: '1'
#    type: REG_DWORD

  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'HideFileExt'
    data: '0'
    type: REG_DWORD

    # show checkboxes next to files
#  - !registryValue:
#    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
#    value: 'AutoCheckSelect'
#    data: '1'
#    type: REG_DWORD
#    option: 'checkmark-yes'

    # set taskbar to left in windows 11
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'TaskbarAl'
    data: '0'
    type: REG_DWORD
    builds: [ '>=22000' ]

    # restore old context menu in windows 11
  - !registryValue:
    path: 'HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32'
    value: ''
    data: ''
    type: REG_SZ
    builds: [ '>=22000' ]

    # decrease explorer.exe bloat in Windows 11
  - !cmd:
    command: '11EXPLORER.bat'
    exeDir: true
    wait: true
    builds: [ '>=22000' ]

    # set explorer.exe default page to "Your PC" in Windows 11
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'LaunchTo'
    data: '1'
    type: REG_DWORD
    builds: [ '>=22000' ]

    # disable annoying USB notifcations (ex. Scan and Fix)
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Shell\USB'
    value: 'NotifyOnUsbErrors'
    data: '0'
    type: REG_DWORD

    # Don't clean up recycle bin automatically
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy', value: '08', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy', value: '256', type: REG_DWORD, data: '0'}

    # add take ownership to context menu (taken from Revi)
  - !registryKey: {path: 'HKCR\*\shell\runas'}
  - !registryValue: {path: 'HKCR\*\shell\runas', value: '', type: REG_SZ, data: 'Take Ownership'}
  - !registryValue: {path: 'HKCR\*\shell\runas', value: 'HasLUAShield', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\*\shell\runas', value: 'NoWorkingDirectory', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\*\shell\runas', value: 'Position', type: REG_SZ, data: 'middle'}
  - !registryValue: {path: 'HKCR\*\shell\runas\command', value: '', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" && icacls "%1" /grant *S-1-3-4:F /c /l'}
  - !registryValue: {path: 'HKCR\*\shell\runas\command', value: 'IsolatedCommand', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" && icacls "%1" /grant *S-1-3-4:F /c /l'}
  - !registryKey: {path: 'HKCR\Directory\shell\runas'}
  - !registryValue: {path: 'HKCR\Directory\shell\runas', value: '', type: REG_SZ, data: 'Take Ownership'}
  - !registryValue: {path: 'HKCR\Directory\shell\runas', value: 'AppliesTo', type: REG_SZ, data: 'NOT (System.ItemPathDisplay:="C:\Users" OR System.ItemPathDisplay:="C:\ProgramData" OR System.ItemPathDisplay:="C:\Windows" OR System.ItemPathDisplay:="C:\Windows\System32" OR System.ItemPathDisplay:="C:\Program Files" OR System.ItemPathDisplay:="C:\Program Files (x86)")'}
  - !registryValue: {path: 'HKCR\Directory\shell\runas', value: 'HasLUAShield', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\Directory\shell\runas', value: 'NoWorkingDirectory', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\Directory\shell\runas', value: 'Position', type: REG_SZ, data: 'middle'}
  - !registryValue: {path: 'HKCR\Directory\shell\runas\command', value: '', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" /r /d y && icacls "%1" /grant *S-1-3-4:F /t /c /l /q'}
  - !registryValue: {path: 'HKCR\Directory\shell\runas\command', value: 'IsolatedCommand', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" /r /d y && icacls "%1" /grant *S-1-3-4:F /t /c /l /q'}
  - !registryKey: {path: 'HKCR\dllfile\shell\runas'}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas', value: '', type: REG_SZ, data: 'Take Ownership'}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas', value: 'HasLUAShield', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas', value: 'NoWorkingDirectory', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas', value: 'Position', type: REG_SZ, data: 'middle'}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas\command', value: '', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" && icacls "%1" /grant *S-1-3-4:F /c /l'}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas\command', value: 'IsolatedCommand', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" && icacls "%1" /grant *S-1-3-4:F /c /l'}
  - !registryKey: {path: 'HKCR\exefile\shell\runas'}
  - !registryValue: {path: 'HKCR\exefile\shell\runas', value: 'HasLUAShield', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\exefile\shell\runas\command', value: '', type: REG_SZ, data: '"%1" %*'}
  - !registryValue: {path: 'HKCR\exefile\shell\runas\command', value: 'IsolatedCommand', type: REG_SZ, data: '"%1" %*'}