title: Sets certain Windows Services to manual in order to decrease background load (taken from Chris Titus Windows Utility).
actions:
  - !cmd:
    command: 'SERVICES.bat'
    exeDir: true
    wait: true