title: Cleans the start menu aka removes ads (thanks to RapidOS-Community at GitHub!)
actions:
- !powerShell:
  command: '.\STARTMENU-CLEANUP.ps1'
  exeDir: true
  wait: true

- !powerShell:
  command: 'Get-AppxPackage Microsoft.Windows.StartMenuExperienceHost | Foreach {Add-AppxPackage -DisableDevelopmentMode -ForceApplicationShutdown -Register "$($_.InstallLocation)\AppXManifest.xml"}'
  wait: true

