title: Changes in the Creosynth playbook
description: Below you may see every change that will occur once you run the playbook.
actions:
  # General tasks
  - !writeStatus: {status: 'Debloating your OS', option: 'debloat-yes'}
  - !task: {path: 'Tasks\debloat.yml', option: 'debloat-yes'}
  - !writeStatus: {status: 'Removing APPX bloat', option: 'remove-appx'}
  - !task: {path: 'Tasks\appx-debloat.yml', option: 'remove-appx'}
  - !writeStatus: {status: 'Removing Microsoft Store', option: 'store-yes'}
  - !task: {path: 'Tasks\remove-store.yml', option: 'store-yes'}
  - !writeStatus: {status: 'Removing Microsoft Edge', option: 'remove-edge'}
  - !task: {path: 'Tasks\edge-remove.yml', option: 'remove-edge'}
  - !writeStatus: {status: 'Debloating Microsoft Edge', option: 'debloat-edge'}
  - !task: {path: 'Tasks\edge-debloat.yml', option: 'debloat-edge'}
  - !writeStatus: {status: 'Removing OneDrive', option: 'remove-onedrive'}
  - !task: {path: 'Tasks\onedrive.yml', option: 'remove-onedrive'}

  - !writeStatus: {status: 'Disabling Security', option: 'disable-security'}
  - !task: {path: 'Tasks\Security\defender.yml', option: 'only-defender'}
  - !task: {path: 'Tasks\Security\other-security.yml', option: 'other-security'}

  - !writeStatus: {status: 'Configuring services', option: 'services-yes'}
  - !task: {path: 'Tasks\services.yml', option: 'services-yes'}
  - !writeStatus: {status: 'Configuring Windows Update', option: 'windows-update'}
  - !task: {path: 'Tasks\updates.yml', option: 'windows-update'}
  - !writeStatus: {status: 'Improving your privacy', option: 'privacy-yes'}
  - !task: {path: 'Tasks\privacy.yml', option: 'privacy-yes'}
  - !writeStatus: {status: 'Applying QoL changes', option: 'qol-yes'}
  - !task: {path: 'Tasks\qol.yml', option: 'qol-yes'}
  - !writeStatus: {status: 'Optimising Windows', option: 'optimise-yes'}
  - !task: {path: 'Tasks\optimise.yml', option: 'optimise-yes'}

  # Installation tasks
  - !writeStatus: {status: 'Installing all VCRuntimes', option: 'vcruntimes'}
  - !task: {path: 'Tasks\vcruntimes.yml', option: 'vcruntimes'}
  - !writeStatus: {status: 'Installing ZwTimerResolution', builds: ['>=22000'], option: zwtimerresolution}
  - !task: {path: 'Tasks\Software\zwt.yml', builds: ['>=22000'], option: zwtimerresolution}
  - !writeStatus: {status: 'Installing FlexASIO + Fluent', option: 'flexasio'}
  - !task: {path: 'Tasks\Software\flexasio.yml', option: 'flexasio'}
  - !writeStatus: {status: 'Installing ExplorerPatcher', option: 'download-explorerpatcher'}
  - !task: {path: 'Tasks\ep.yml', option: 'download-explorerpatcher'}
  - !writeStatus: {status: 'Move the AME Wizard window away...', option: 'unified-hosts-autoupdate'}
  - !task: {path: 'Tasks\Software\unified-hosts-autoupdate.yml', option: 'unified-hosts-autoupdate'}
  - !writeStatus: {status: 'Installing Chocolatey', option: 'download-choco'}
  - !task: {path: 'Tasks\Software\chocolatey.yml', option: 'download-choco'}
  - !writeStatus: {status: 'Installing Scoop', option: 'download-scoop'}
  - !task: {path: 'Tasks\Software\chocolatey.yml', option: 'download-scoop'}